#!/usr/bin/env bash
set -euo pipefail

_FRP_INSTALL_CLIENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" ]] || {
  echo "ERROR: missing project file: ${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" >&2
  exit 1
}
# shellcheck source=lib/frp-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh"
frp_export_drlink_env_aliases
# shellcheck source=lib/frp-client-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh"

frp_valid_allocator_url() {
  local url="${1:-}"
  case "$url" in
    http://?*)
      return 1
      ;;
    https://?*) ;;
    *) return 1 ;;
  esac
  if [[ "$url" == *$'\n'* || "$url" == *$'\r'* || "$url" == *$'\t'* || "$url" == *' '* ]]; then
    return 1
  fi
  local rest="${url#*://}"
  local hostport="${rest%%/*}"
  [[ -n "$hostport" ]]
}

frp_require_allocator_url() {
  local url="${FRP_ALLOCATOR_URL:-}"
  if [[ -z "$url" ]]; then
    echo "ERROR: FRP allocator URL is not configured." >&2
    echo "Set FRP_ALLOCATOR_URL or use the installer command generated by: sudo drlink set client (or sudo drlink set enrollment)." >&2
    exit 1
  fi
  if [[ "$url" == http://* ]]; then
    echo "ERROR: plain HTTP allocator URL is not supported; HTTPS is required." >&2
    exit 1
  fi
  if ! frp_valid_allocator_url "$url"; then
    echo "ERROR: FRP allocator URL is invalid; an https:// URL with a host is required." >&2
    exit 1
  fi
  ALLOCATOR_URL="$url"
}

menu_add_service() {
  local payload=""
  frp_ux_prompt_new_service payload
  if [[ -z "$payload" ]]; then
    return 0
  fi
  if ! services_add_json "$payload"; then
    return 0
  fi
}

menu_remove_service() {
  local choice
  if [[ "$(services_count)" == "0" ]]; then
    echo "ERROR: no services to remove" >&2
    return 0
  fi
  echo
  echo "Configured services"
  echo "==================="
  echo
  services_list
  echo "Remove from this install list only."
  echo "Nothing has been published yet, so no public port is reserved."
  echo
  choice="$(read_tty "Remove service number: " "")"
  if ! services_remove_index "$choice"; then
    return 0
  fi
}

collect_services_interactive() {
  local choice payload
  while true; do
    echo
    if [[ "$(services_count)" == "0" ]]; then
      frp_ux_empty_services_help
      echo "1) Add service"
      echo "2) Remove a service"
      echo "3) Cancel"
      echo
      choice="$(read_tty "Select an option [1]: " "1")"
      case "$choice" in
        1) menu_add_service ;;
        2) menu_remove_service ;;
        3)
          echo "Cancelled."
          return 1
          ;;
        *) echo "ERROR: select 1-3" >&2 ;;
      esac
    else
      echo "Configured services"
      echo "==================="
      echo
      services_list
      frp_ux_configured_services_help
      echo "1) Add another service"
      echo "2) Remove a service"
      echo "3) Install and connect"
      echo "4) Cancel"
      echo
      choice="$(read_tty "Select: " "")"
      case "$choice" in
        1) menu_add_service ;;
        2) menu_remove_service ;;
        3)
          frp_ux_print_install_summary "$SERVICES_FILE" "$FRP_VERSION"
          if frp_confirm_yes "Continue? [Y/n]: "; then
            return 0
          fi
          echo "Returning to the service configuration menu."
          ;;
        4)
          echo "Cancelled."
          return 1
          ;;
        *) echo "ERROR: select 1-4" >&2 ;;
      esac
    fi
  done
}

collect_services() {
  services_init
  if [[ -n "${FRP_SERVICES_JSON:-}" ]]; then
    # An explicit empty list is management-only enrollment, not a mistake:
    # the variable is only consulted when it was set to a non-empty value.
    services_load_from_env
    return 0
  fi
  collect_services_interactive || return 1
}

print_complete() {
  local server="$1" services_json_file="$2" alias="${3:-}"
  if [[ -z "$alias" && -f "$services_json_file" ]]; then
    alias="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1],encoding="utf-8")); print(d.get("public_hostname","") if isinstance(d,dict) else "")' "$services_json_file" 2>/dev/null || true)"
  fi
  if frp_zero_touch_active || [[ "${FRP_ZERO_TOUCH_COMPLETE:-}" == "1" ]]; then
    python3 - "$server" "$services_json_file" "$alias" <<'PY'
import json, sys
from pathlib import Path
server = sys.argv[1]
raw = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
alias = (sys.argv[3] or '').strip()
if isinstance(raw, dict) and 'services' in raw:
    services = list((raw.get('services') or {}).values())
    if not alias:
        alias = str(raw.get('public_hostname') or '').strip()
else:
    services = raw
preferred = alias if alias and alias != server else ''
def host_for_url(text):
    text = str(text or '').strip()
    if not text:
        return text
    if text.startswith('[') and text.endswith(']'):
        return text
    try:
        import ipaddress
        if isinstance(ipaddress.ip_address(text), ipaddress.IPv6Address):
            return '[%s]' % text
    except ValueError:
        pass
    return text
print()
print('Data Relay Link client setup complete.')
print()
if not services:
    print('Management identity enrolled (management-only mode).')
    print('No services are published and no public ports were allocated.')
    print('Add a service later with: sudo drlink')
else:
    print('Enrollment finished. Review Remote Service status with:')
    print('  sudo drlink show remote-services')
print('You can close this terminal.')
print()
for item in services:
    if item.get('enabled', True) is False:
        continue
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    host = preferred or server
    if preset == 'ssh':
        user = item.get('ssh_user') or '<username>'
        print('SSH tunnel ready')
        print()
        print('Connect:')
        if not item.get('ssh_user'):
            print('  (SSH username is connection-example metadata; not validated at enrollment)')
        if preferred:
            print('  Preferred:')
            print('    ssh -p %s %s@%s' % (remote_port, user, preferred))
            print('  Fallback:')
            print('    ssh -p %s %s@%s' % (remote_port, user, server))
        else:
            print('  ssh -p %s %s@%s' % (remote_port, user, server))
        print()
    elif preset == 'http':
        print('Connect:')
        if preferred:
            print('  Preferred:')
            print('    http://%s:%s' % (host_for_url(preferred), remote_port))
            print('  Fallback:')
            print('    http://%s:%s' % (host_for_url(server), remote_port))
        else:
            print('  http://%s:%s' % (host_for_url(server), remote_port))
        print()
    elif preset == 'https':
        print('Connect:')
        if preferred:
            print('  Preferred:')
            print('    https://%s:%s' % (host_for_url(preferred), remote_port))
            print('  Fallback:')
            print('    https://%s:%s' % (host_for_url(server), remote_port))
        else:
            print('  https://%s:%s' % (host_for_url(server), remote_port))
        print()
    else:
        print('Connect:')
        if preferred:
            print('  Preferred:')
            print('    %s:%s' % (preferred, remote_port))
            print('  Fallback:')
            print('    %s:%s' % (server, remote_port))
        else:
            print('  %s:%s' % (server, remote_port))
        print()
PY
    return 0
  fi
  python3 - "$server" "$services_json_file" "$(frp_os)" "$alias" <<'PY'
import json,sys
from pathlib import Path
server = sys.argv[1]
raw = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
alias = (sys.argv[4] if len(sys.argv) > 4 else '').strip()
if isinstance(raw, dict) and 'services' in raw:
    services = list((raw.get('services') or {}).values())
    if not alias:
        alias = str(raw.get('public_hostname') or '').strip()
else:
    services = raw
preferred = alias if alias and alias != server else ''
def host_for_url(text):
    text = str(text or '').strip()
    if not text:
        return text
    if text.startswith('[') and text.endswith(']'):
        return text
    try:
        import ipaddress
        if isinstance(ipaddress.ip_address(text), ipaddress.IPv6Address):
            return '[%s]' % text
    except ValueError:
        pass
    return text
print()
print('=========================================')
print(' Data Relay Link Installation Complete')
print('=========================================')
print()
print('Your Data Relay Link client is running successfully.')
print()
print('Published services')
print('------------------')
print()
for item in services:
    name = item.get('name') or item['id']
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    print(name)
    print(f"  Local target : {item.get('local_ip')}:{item.get('local_port')}")
    print(f"  Public port  : {remote_port}")
    print()
    if preset == 'ssh':
        user = item.get('ssh_user')
        if user:
            print('Connect from another machine with:')
            print()
            if preferred:
                print('  Preferred:')
                print(f'    ssh -p {remote_port} {user}@{preferred}')
                print('  Fallback:')
                print(f'    ssh -p {remote_port} {user}@{server}')
            else:
                print(f'  ssh -p {remote_port} {user}@{server}')
        else:
            print('SSH user: legacy / unspecified')
    elif preset == 'http':
        print('Access:')
        print()
        if preferred:
            print('  Preferred:')
            print(f'    http://{preferred}:{remote_port}')
            print('  Fallback:')
            print(f'    http://{server}:{remote_port}')
        else:
            print(f'  http://{server}:{remote_port}')
    elif preset == 'https':
        print('Access:')
        print()
        if preferred:
            print('  Preferred:')
            print(f'    https://{preferred}:{remote_port}')
            print('  Fallback:')
            print(f'    https://{server}:{remote_port}')
        else:
            print(f'  https://{server}:{remote_port}')
    else:
        print('Connect:')
        print()
        if preferred:
            print('  Preferred:')
            print(f'    {preferred}:{remote_port}')
            print('  Fallback:')
            print(f'    {server}:{remote_port}')
        else:
            print(f'  {server}:{remote_port}')
    print()
print('For normal operation, this is the only command you need to remember:')
print()
print('  sudo drlink')
print()
print('Then type help or ? inside the CLI.')
print()
print('Useful commands')
print('---------------')
print()
print('Everyday CLI / status / doctor / update:')
print('  sudo drlink')
print('  sudo drlink show status')
print('  sudo drlink system diagnostics')
print('  sudo drlink system update product')
print()
print('Local client details:')
print('  sudo drlink system info')
print()
if sys.argv[3] == 'darwin':
    print('launchd daemon:')
    print('  sudo launchctl print system/com.datarelay.drlink.frpc')
else:
    print('Systemd service:')
    print('  sudo systemctl status drlink-client --no-pager')
print()
print('=========================================')
PY
}

frp_client_install_service_definition() {
  if frp_is_darwin; then
    frp_macos_launchd_install
    # macOS durable AI worker lifecycle is not claimed in this packet; Linux is
    # the mandatory Managed Host AI executor path. macOS remains fail-closed
    # (no local AI worker) until a later platform-support packet.
    return
  fi
  # Retire product-owned legacy frpc.service before enabling the canonical unit.
  # Fail closed: never proceed when an active product-owned legacy supervisor remains.
  frp_retire_legacy_client_unit || return 1
  local unit_src="${_FRP_INSTALL_CLIENT_DIR}/client/drlink-client.service"
  if [[ -f "$unit_src" ]]; then
    frp_write_compatible_systemd_unit "$unit_src" /etc/systemd/system/drlink-client.service
  else
    cat >/etc/systemd/system/drlink-client.service <<'EOF2'
[Unit]
Description=Data Relay Link Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF2
  fi
  local ai_unit_src="${_FRP_INSTALL_CLIENT_DIR}/client/drlink-ai-agent.service"
  if [[ -f "$ai_unit_src" ]]; then
    frp_write_compatible_systemd_unit "$ai_unit_src" /etc/systemd/system/drlink-ai-agent.service
  else
    cat >/etc/systemd/system/drlink-ai-agent.service <<'EOF3'
[Unit]
Description=Data Relay Link AI Agent Worker
After=network-online.target drlink-client.service
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/local/lib/drlink/drlink_ai_agent.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF3
  fi
}

frp_client_service_reload() {
  frp_is_darwin || systemctl daemon-reload
}

# Record relay verification only when wait_for_proxies succeeds.
# A local target socket is not evidence. Failure leaves the flag unset/0.
frp_client_note_enrolled_proxies_verified() {
  if ! wait_for_proxies "$@"; then
    FRP_ENROLLED_PROXIES_VERIFIED=0
    return 1
  fi
  FRP_ENROLLED_PROXIES_VERIFIED=1
  return 0
}

# Pass the flag only into this python3 process. Test roots and FRP_SKIP_SYSTEMD
# never ran wait_for_proxies, so they stay runtime_verified=False.
frp_client_activate_enrolled_services() {
  local verified=0
  if [[ "${1:-0}" == "1" && "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    verified=1
  fi
  FRP_ENROLLED_PROXIES_VERIFIED="$verified" python3 -c '
import os, sys
from pathlib import Path
root = os.environ.get("FRP_CLIENT_TEST_ROOT") or os.environ.get("FRP_DEPLOY_TEST_ROOT") or ""
cands = []
if root:
    cands.append(Path(root) / "usr/local/lib/drlink")
cands.append(Path("/usr/local/lib/drlink"))
here = Path(os.environ.get("_FRP_INSTALL_CLIENT_DIR") or ".")
cands.extend([here / "lib", here.parent / "lib"])
for base in cands:
    if (base / "drlink_v24.py").is_file():
        sys.path.insert(0, str(base))
        break
try:
    import drlink_v24 as v24
except Exception:
    raise SystemExit(0)
verified = os.environ.get("FRP_ENROLLED_PROXIES_VERIFIED") == "1"
results = v24.activate_enrolled_services_as_remote_services(
    root=root or None,
    runtime_verified=verified,
)
healthy = False
degraded = []
for result in results:
    view = (result or {}).get("view") or {}
    status = str(view.get("status") or "")
    name = view.get("name") or "?"
    if status == "HEALTHY":
        healthy = True
        print("Remote Service activated: %s (%s)" % (name, view.get("endpoint") or "-"))
    elif status:
        degraded.append((name, status, view.get("reason") or ""))
for name, status, reason in degraded:
    print("Remote Service not fully activated: %s status=%s" % (name, status))
    if reason:
        print("  Reason: %s" % reason)
if results and not healthy and degraded:
    print("Zero-Touch enrollment finished, but Remote Service activation is incomplete.")
    print("Run: sudo drlink show remote-services")
' || true
}

frp_client_service_start() {
  if frp_is_darwin; then
    frp_macos_launchd_set_enabled enable || return 1
    frp_macos_launchd_bootout
    frp_macos_launchd_bootstrap || return 1
  else
    frp_retire_legacy_client_unit || return 1
    systemctl enable drlink-client >/dev/null && systemctl restart drlink-client
    # Durable AI worker. Connectivity install still proceeds if the worker
    # cannot start; product update fails closed when the same converge fails.
    frp_client_converge_ai_agent_unit "${_FRP_INSTALL_CLIENT_DIR:-}" || true
  fi
}

frp_client_reconcile_installed_permissions() {
  local f
  for f in "$(frp_client_state_path)" "$(frp_client_toml_path)" \
    "$(frp_client_identity_key_path)" "$(frp_client_identity_pub_path)" \
    "$(frp_client_identity_mac_path)"; do
    if [[ -f "$f" ]]; then
      chmod 600 "$f" 2>/dev/null || true
    fi
  done
  if [[ -x "$(frp_client_path /usr/local/bin/drlink)" ]]; then
    chmod 0755 "$(frp_client_path /usr/local/bin/drlink)" 2>/dev/null || true
  fi
  if [[ -x "$(frp_client_path /usr/bin/drlink)" ]]; then
    chmod 0755 "$(frp_client_path /usr/bin/drlink)" 2>/dev/null || true
  fi
  if [[ -x "$(frp_client_path /usr/local/bin/frpc)" ]]; then
    chmod 0755 "$(frp_client_path /usr/local/bin/frpc)" 2>/dev/null || true
  fi
}

frp_client_repair_partial_install() {
  local source="${1:-${_FRP_INSTALL_CLIENT_DIR}}"
  echo "A partial or broken Data Relay Link client installation was found." >&2
  echo "Restoring missing client software without changing this client's identity." >&2
  frp_client_install_management_files "$source" || return 1
  if [[ -z "${FRP_CLIENT_TEST_ROOT:-}" && "${FRP_SKIP_SYSTEMD:-}" != "1" ]]; then
    frp_client_install_service_definition || return 1
    frp_client_service_reload || return 1
    if ! frp_is_darwin; then
      systemctl enable drlink-client >/dev/null 2>&1 || true
    fi
  fi
  frp_client_reconcile_installed_permissions
  if ! frp_client_has_existing_install; then
    echo "ERROR: the partial installation could not be repaired into a complete client." >&2
    echo "Identity and configuration were left unchanged." >&2
    frp_client_partial_recovery_guidance
    frp_emit_failure_class RECOVERY_REQUIRED
    return 1
  fi
  echo "Repair complete. Existing client identity and configuration were preserved." >&2
  echo "This client was not re-enrolled." >&2
  if frp_zero_touch_active; then
    echo "The Bootstrap Ticket was not used." >&2
  fi
  echo "Use sudo drlink show status to inspect this client." >&2
  return 0
}

frp_client_partial_recovery_guidance() {
  echo "ERROR: a partial or broken Data Relay Link client installation was found." >&2
  if command -v drlink >/dev/null 2>&1 || [[ -x "$(frp_client_path /usr/local/bin/drlink)" ]]; then
    echo "Repair it with: sudo drlink system update product" >&2
  else
    echo "This host is not a complete current Data Relay Link client." >&2
    echo "Re-run the exact same bootstrap-client.sh installer command to restore" >&2
    echo "missing software from local recovery state (the Bootstrap Ticket is not reused)." >&2
    if [[ -x "$(frp_client_path /usr/local/sbin/uninstall-client.sh)" ]] \
      || [[ -x "$(frp_client_path /usr/local/bin/uninstall-client.sh)" ]]; then
      echo "Or uninstall locally, then enroll again from the server." >&2
    fi
  fi
  echo "Do not invent a new Enrollment Code for a reserved partial client." >&2
}

frp_client_existing_install_message() {
  if frp_zero_touch_active; then
    echo "This client is already installed." >&2
    echo "Use sudo drlink system update product." >&2
    return 0
  fi
  echo "ERROR: this host already has a Data Relay Link client installed." >&2
  echo >&2
  echo "A software update must not re-enroll the client and does not" >&2
  echo "require an Enrollment Code." >&2
  echo >&2
  echo "Upgrade in place with:" >&2
  echo "  sudo drlink system update product" >&2
  echo >&2
  local upgrade_ref upgrade_url
  upgrade_ref="$(frp_client_installed_source_ref 2>/dev/null || true)"
  if [[ -z "$upgrade_ref" || "$upgrade_ref" == "unknown" ]]; then
    upgrade_ref="$(frp_release_git_ref 2>/dev/null || true)"
  fi
  if [[ -z "$upgrade_ref" || "$upgrade_ref" == "unknown" ]]; then
    upgrade_ref="$(frp_read_kv_file "$(frp_version_state_file)" SOURCE_REF 2>/dev/null || true)"
  fi
  if [[ -n "$upgrade_ref" && "$upgrade_ref" != "unknown" ]]; then
    upgrade_url="https://${FRP_GITHUB_RAW_HOST}/${FRP_GITHUB_OWNER}/${FRP_GITHUB_REPO}/${upgrade_ref}/dist/bootstrap-client.sh"
    echo "or, from the bootstrap bundle for this install's source ref (${upgrade_ref}):" >&2
    echo "  curl -fsSL ${upgrade_url} | sudo bash -s -- --upgrade" >&2
  else
    echo "or re-run the same bootstrap-client.sh --upgrade command used for this install." >&2
  fi
  echo >&2
  echo "Use sudo drlink to change published services." >&2
  echo "An Enrollment Code is only for first install or trust recovery." >&2
}

frp_client_upgrade_from_this_tree() {
  local source="${FRP_CLIENT_UPDATE_SOURCE:-${_FRP_INSTALL_CLIENT_DIR}}"
  local check_only=0
  local kind="bundle"
  if [[ "${FRP_CLIENT_UPDATE_CHECK:-}" == "1" ]]; then
    check_only=1
  fi
  if [[ -n "${FRP_CLIENT_UPDATE_SOURCE:-}" ]]; then
    kind="source"
  fi
  _FRP_CLIENT_UPDATE_KIND="$kind" frp_client_apply_upgrade "$source" "$check_only"
}

frp_client_main() {
  if [[ ${EUID} -ne 0 && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "ERROR: run as root, e.g. curl ... | sudo env FRP_ALLOCATOR_URL=... bash" >&2
    exit 1
  fi

  # Resolve machine ID without creating client directories yet. Missing URL must
  # fail closed before any partial install tree is written (CASE B).
  if [[ -n "${FRP_TEST_MACHINE_ID:-}" ]]; then
    MACHINE_ID="$FRP_TEST_MACHINE_ID"
  elif frp_is_darwin; then
    MACHINE_ID="$(frp_macos_machine_id)" || exit 1
  elif [[ -s /etc/machine-id ]]; then
    MACHINE_ID="$(tr -d '\n' </etc/machine-id)"
  elif [[ -s "$(frp_client_path /etc/frp/client-id)" ]]; then
    MACHINE_ID="$(tr -d '\n' <"$(frp_client_path /etc/frp/client-id)")"
  else
    MACHINE_ID="$(openssl rand -hex 16)"
  fi

  FRP_RESUME_PENDING=0
  if frp_pending_enroll_exists_for "$MACHINE_ID"; then
    FRP_RESUME_PENDING=1
    if [[ -z "${FRP_ALLOCATOR_URL:-}" ]]; then
      FRP_ALLOCATOR_URL="$(frp_pending_enroll_allocator_url || true)"
    fi
  fi

  if frp_client_has_existing_install; then
    frp_client_existing_install_message
    return 1
  fi
  if frp_client_has_partial_install && [[ "$FRP_RESUME_PENDING" != "1" ]]; then
    if frp_client_partial_is_safe_to_repair; then
      frp_client_repair_partial_install "${_FRP_INSTALL_CLIENT_DIR}" || return 1
      return 0
    fi
    frp_client_partial_recovery_guidance
    frp_emit_failure_class RECOVERY_REQUIRED
    return 1
  fi

  frp_require_allocator_url

  local etc_frp
  etc_frp="$(frp_client_path /etc/frp)"
  mkdir -p "$etc_frp"
  if [[ ! -s "${etc_frp}/client-id" ]]; then
    printf '%s\n' "$MACHINE_ID" >"${etc_frp}/client-id"
    chmod 600 "${etc_frp}/client-id"
  fi

  if frp_zero_touch_active; then
    frp_zero_touch_require_inputs || return 1
  fi
  frp_bootstrap_allocator_ca "$ALLOCATOR_URL" || return 1
  frp_detect_os >/dev/null || exit 1
  frp_detect_architecture || exit 1

  if [[ -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    if frp_is_darwin; then
      frp_macos_require_supported_release || exit 1
      frp_macos_print_detected
      echo
      frp_require_service_manager || exit 1
      frp_macos_require_dependencies || {
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        exit 1
      }
      frp_require_python || exit 1
      frp_macos_ensure_dirs || exit 1
    else
      frp_require_bash || exit 1
      frp_detect_platform
      frp_detect_package_manager
      frp_print_detected_linux
      echo
      frp_require_service_manager || exit 1
      FRP_DEPENDENCY_ROLE=client
      if [[ "${FRP_INSTALL_HOOK_DEP_FAIL:-}" == "1" ]]; then
        echo "ERROR: simulated package manager failure" >&2
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        exit 1
      fi
      ensure_dependencies || {
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        exit 1
      }
      frp_require_python || exit 1
    fi
  fi

  SERVICES_FILE="$(mktemp)"
  ALLOCATED_FILE="$(mktemp)"
  ENROLL_META_FILE="$(mktemp)"
  TMPDIR="$(frp_secure_mktemp_dir)"
  chmod 600 "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"
  _frp_client_enroll_tmp_cleanup() {
    rm -rf "$TMPDIR" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"
    unset FRP_TOKEN ENROLL_SECRET FRP_ENROLLMENT_CODE TOKEN_CIPHERTEXT FRP_BOOTSTRAP_TICKET
  }
  # Sourced callers (tests, frpctl wrappers) already own EXIT. Replacing or
  # chaining that trap leaks test allocators or SIGSEGVs bash on restore.
  if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    trap '_frp_client_enroll_tmp_cleanup' EXIT
  fi

  RESUME_PHASE=""
  if [[ "$FRP_RESUME_PENDING" == "1" ]]; then
    echo "A previous enrollment did not finish (response lost or interrupted)." >&2
    echo "Resuming from local crash-safe recovery state; the Bootstrap Ticket is not reused." >&2
    if ! frp_pending_enroll_load "$MACHINE_ID" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE" \
      RESUME_PHASE ENROLL_ID ENROLL_SECRET; then
      echo "ERROR: local recovery state is present but unusable." >&2
      echo "Create a new Enrollment Code and re-enroll this client." >&2
      frp_emit_failure_class RECOVERY_REQUIRED
      return 1
    fi
    FRP_ZERO_TOUCH_COMPLETE=1
    FRP_SERVICES_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1],encoding="utf-8"))))' "$SERVICES_FILE")"
    export FRP_SERVICES_JSON
    services_load_from_env
    unset FRP_SERVICES_JSON
  elif frp_zero_touch_active; then
    :
  else
    frp_ux_intro
    frp_ux_enrollment_help
    prompt_secret "Enrollment Code: " FRP_ENROLLMENT_CODE

    if [[ "$FRP_ENROLLMENT_CODE" != *.* ]]; then
      echo "ERROR: invalid enrollment code format" >&2
      exit 1
    fi
    ENROLL_ID="${FRP_ENROLLMENT_CODE%%.*}"
    ENROLL_SECRET="${FRP_ENROLLMENT_CODE#*.}"
    collect_services
  fi

  HOSTNAME_VALUE="$(frp_short_hostname)"

  if frp_zero_touch_active; then
    local ssh_user ssh_port
    ssh_user="${FRP_SSH_USER:-}"
    ssh_port="${FRP_SSH_PORT:-22}"
    if [[ -n "$ssh_user" ]]; then
      frp_zero_touch_ssh_preflight "$ssh_user" "$ssh_port" || return 1
    fi
  fi

  if ! frp_identity_ensure; then
    exit 1
  fi

  if [[ "$FRP_RESUME_PENDING" == "1" ]]; then
    : # Enrollment Code/Ticket was already redeemed in a prior attempt; a
      # Bootstrap Ticket is single-use and must not be redeemed again.
  elif frp_zero_touch_active; then
    echo "Completing one-time setup ..."
    if ! frp_redeem_bootstrap_ticket "$ALLOCATOR_URL" "$MACHINE_ID" "$HOSTNAME_VALUE" \
      "$SERVICES_FILE" ENROLL_ID ENROLL_SECRET; then
      return 1
    fi
    FRP_ZERO_TOUCH_COMPLETE=1
    FRP_SERVICES_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1],encoding="utf-8"))))' "$SERVICES_FILE")"
    export FRP_SERVICES_JSON
    services_load_from_env
    unset FRP_SERVICES_JSON
  fi

  if [[ "$FRP_RESUME_PENDING" == "1" && "$RESUME_PHASE" == "enrolled" ]]; then
    # The server-committed /enroll response was cached locally before the
    # prior crash; finish the local commit without another network round
    # trip or ticket/enrollment-code reuse.
    echo "Reusing the previously completed enrollment response ..."
  else
    # Persist the enrollment secret and exact request now, before calling
    # /enroll, so a crash after the server commits (but before the response
    # is received or written) can be recovered by an exact replay instead of
    # requiring a new Enrollment Code.
    frp_pending_enroll_write redeemed "$MACHINE_ID" "$HOSTNAME_VALUE" "$ALLOCATOR_URL" \
      "$ENROLL_ID" "$ENROLL_SECRET" "$SERVICES_FILE"
    echo "Validating enrollment and requesting persistent public ports ..."
    frp_enroll_services "$ALLOCATOR_URL" "$ENROLL_ID" "$ENROLL_SECRET" \
      "$MACHINE_ID" "$HOSTNAME_VALUE" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE" \
      || exit 1
    frp_pending_enroll_write enrolled "$MACHINE_ID" "$HOSTNAME_VALUE" "$ALLOCATOR_URL" \
      "$ENROLL_ID" "$ENROLL_SECRET" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"
    if [[ "${FRP_CLIENT_HOOK_CRASH_AFTER_ENROLL:-}" == "1" ]]; then
      # Test-only: simulate a crash/lost response after the allocator has
      # committed the enrollment and the response was cached locally, but
      # before any further local commit step runs.
      echo "ERROR: simulated crash after enrollment commit" >&2
      exit 1
    fi
  fi
  FRP_SERVER="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server"])' "$ENROLL_META_FILE")"
  FRP_SERVER_PORT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server_port"])' "$ENROLL_META_FILE")"
  FRP_PUBLIC_HOSTNAME="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8")).get("public_hostname",""))' "$ENROLL_META_FILE")"
  FRP_TRANSPORT="$(python3 -c 'import json,sys; print((json.load(open(sys.argv[1],encoding="utf-8")).get("frp_transport") or "tcp"))' "$ENROLL_META_FILE")"
  TOKEN_CIPHERTEXT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["token_ciphertext"])' "$ENROLL_META_FILE")"
  merge_allocated_services
  FRP_TOKEN="$(frp_decrypt_token "$TOKEN_CIPHERTEXT" "$ENROLL_SECRET")" || exit 1

  if [[ -z "${FRP_ARCH:-}" ]]; then
    frp_detect_architecture || exit 1
  fi

  # Before restoring /usr/local/bin/frpc: an enabled leftover frpc.service with
  # Restart=always will respawn as soon as the binary reappears (E2E-001).
  # Fail closed if a product-owned legacy supervisor cannot be stopped.
  if ! frp_is_darwin; then
    frp_retire_legacy_client_unit || exit 1
  fi

  if [[ "${FRP_SKIP_DOWNLOAD:-}" != "1" ]]; then
    ARCHIVE="$TMPDIR/frp.tar.gz"
    if [[ -z "${ALLOCATOR_URL:-}" ]]; then
      frp_qualified_artifact_missing "$(frp_os)" "$FRP_ARCH"
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    URL="$(frp_server_local_frp_url "$ALLOCATOR_URL" "$(frp_os)" "$FRP_ARCH")" || {
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    }
    if frp_is_public_frp_download_url "$URL"; then
      frp_qualified_artifact_missing "$(frp_os)" "$FRP_ARCH"
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    echo "Installing qualified FRP ${FRP_VERSION} ($(frp_os)/${FRP_ARCH}) from DRLink Server ..."
    if [[ "${FRP_INSTALL_HOOK_DOWNLOAD_FAIL:-}" == "1" ]]; then
      frp_qualified_artifact_missing "$(frp_os)" "$FRP_ARCH"
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    if ! frp_allocator_curl -fL --proto '=https' --tlsv1.2 --retry 3 -o "$ARCHIVE" "$URL"; then
      frp_qualified_artifact_missing "$(frp_os)" "$FRP_ARCH"
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    echo "Verifying checksum ..."
    if frp_is_darwin; then
      frp_macos_sha256_check "$EXPECTED_SHA" "$ARCHIVE" || {
        python3 "$(frp_qualified_artifacts_py)" verify \
          --file "$ARCHIVE" --sha256 "$EXPECTED_SHA" --kind FRP \
          --platform "$(frp_os)" --architecture "$FRP_ARCH" >/dev/null 2>&1 || true
        echo "ERROR:" >&2
        echo "Qualified FRP artifact failed verification." >&2
        echo "No changes were applied." >&2
        frp_emit_failure_class INTEGRITY_FAILED
        exit 1
      }
    else
      if ! printf '%s  %s\n' "$EXPECTED_SHA" "$ARCHIVE" | sha256sum -c -; then
        echo "ERROR:" >&2
        echo "Qualified FRP artifact failed verification." >&2
        echo "No changes were applied." >&2
        frp_emit_failure_class INTEGRITY_FAILED
        exit 1
      fi
    fi
    extracted="$(frp_extract_frp_member "$ARCHIVE" "$TMPDIR" frpc)" || {
      frp_emit_failure_class STAGING_FAILED
      exit 1
    }
    frp_validate_frp_binary "$extracted" "$FRP_VERSION" "$FRP_ARCH" || {
      frp_emit_failure_class INTEGRITY_FAILED
      exit 1
    }
    frp_atomic_install "$extracted" "$(frp_client_path /usr/local/bin/frpc)" 0755 || {
      frp_emit_failure_class FILE_COMMIT_FAILED
      exit 1
    }
  fi

  HOST_SAFE="$(printf '%s' "$HOSTNAME_VALUE" | tr -cs 'A-Za-z0-9._-' '-')"
  HOST_ID="${HOST_SAFE}-${MACHINE_ID:0:8}"
  FRPC_TOML="$(frp_client_path /etc/frp/frpc.toml)"
  ACCESS_INFO="$(frp_client_path /etc/frp/access-info.txt)"
  mkdir -p "$(dirname "$FRPC_TOML")"
  echo "Validating configuration ..."
  render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" "$SERVICES_FILE" "${FRP_TRANSPORT:-tcp}"
  frp_client_verify_config "$FRPC_TOML" || exit 1

  # Install management/recovery tooling before runtime start so a later
  # service/proxy failure still leaves a discoverable recovery command.
  frp_client_install_management_files "${_FRP_INSTALL_CLIENT_DIR}"

  FRP_ENROLLED_PROXIES_VERIFIED=0
  if [[ "$(services_count)" != "0" && "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "Installing $(frp_service_manager) service ..."
    frp_client_install_service_definition || {
      frp_emit_failure_class FILE_COMMIT_FAILED
      exit 1
    }
    echo "Starting Data Relay Link client ..."
    FRP_PROXY_WAIT_CURSOR="$(frp_client_journal_cursor 2>/dev/null || true)"
    export FRP_PROXY_WAIT_CURSOR
    frp_client_service_reload || {
      frp_emit_failure_class SYSTEMD_RELOAD_FAILED
      exit 1
    }
    if ! frp_client_service_start; then
      echo "ERROR: Data Relay Link client failed to start; local files were written and the server reservation is preserved." >&2
      echo "Recovery: sudo drlink system update product" >&2
      echo "or re-run the same bootstrap installer (Bootstrap Ticket is not reused)." >&2
      frp_emit_failure_class SERVICE_START_FAILED
      exit 1
    fi

    echo "Verifying published proxies ..."
    PROXY_NAMES=()
    while IFS= read -r proxy_name; do
      [[ -n "$proxy_name" ]] && PROXY_NAMES+=("$proxy_name")
    done < <(proxy_names_from_services "$HOST_ID")
    if ! frp_client_note_enrolled_proxies_verified "${PROXY_NAMES[@]}"; then
      echo "ERROR: Relay Engine (FRP) did not register every requested proxy successfully" >&2
      frp_client_recent_runtime_logs 80 >&2 || true
      echo "Recovery: sudo drlink system diagnostics" >&2
      echo "Then: sudo drlink system update product" >&2
      frp_emit_failure_class HEALTH_CHECK_FAILED
      exit 1
    fi
  elif [[ "$(services_count)" == "0" ]]; then
    echo "Management-only mode: frpc is not started until a service is enabled."
    if [[ "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
      echo "Installing inactive $(frp_service_manager) service for future services ..."
      frp_client_install_service_definition || {
        frp_emit_failure_class FILE_COMMIT_FAILED
        exit 1
      }
      frp_client_service_reload || {
        frp_emit_failure_class SYSTEMD_RELOAD_FAILED
        exit 1
      }
    fi
  fi

  render_access_info "$ACCESS_INFO" "$FRP_SERVER" "$SERVICES_FILE" "${FRP_PUBLIC_HOSTNAME:-}"
  frp_write_client_state "$(frp_client_state_path)" "$ALLOCATOR_URL" "$FRP_SERVER" \
    "$FRP_SERVER_PORT" "$HOSTNAME_VALUE" "$MACHINE_ID" "$HOST_ID" "$SERVICES_FILE" \
    "${FRP_TRANSPORT:-tcp}" "${FRP_PUBLIC_HOSTNAME:-}"
  frp_state_has_secrets "$(frp_client_state_path)" || {
    echo "ERROR: client-state.json must not contain secrets" >&2
    exit 1
  }
  # Reconcile frpc.toml from the committed client-state so Doctor never reports
  # immediate frpc_config drift after a clean Zero-Touch install.
  if [[ "$(services_count)" != "0" ]]; then
    if ! render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" \
      "$(frp_client_state_path)" "${FRP_TRANSPORT:-tcp}"; then
      # Fall back to the enrollment services file if state-shaped render fails.
      render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" \
        "$SERVICES_FILE" "${FRP_TRANSPORT:-tcp}" || {
        echo "ERROR: failed to reconcile frpc.toml with client-state.json" >&2
        exit 1
      }
    fi
    frp_client_verify_config "$FRPC_TOML" || exit 1
  fi

  # Local state (client-state.json + frpc.toml + management identity, all
  # written above) is now committed. The crash-safe recovery transaction is
  # no longer needed; clear it so it is never replayed against a future,
  # unrelated Enrollment Code.
  frp_pending_enroll_clear

  # Promote enrolled services into v2.4 Remote Services (reuse allocated ports).
  # The flag is a command-scoped environment value, not a leaked shell export.
  if [[ "$(services_count)" != "0" ]]; then
    frp_client_activate_enrolled_services "${FRP_ENROLLED_PROXIES_VERIFIED:-0}"
  fi
  unset FRP_ENROLLED_PROXIES_VERIFIED

  print_complete "$FRP_SERVER" "$SERVICES_FILE" "${FRP_PUBLIC_HOSTNAME:-}"
  if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
    _frp_client_enroll_tmp_cleanup
  fi
}

frp_client_installer_usage() {
  cat <<'EOF'
Usage: install-client.sh [--upgrade] [--source DIR] [--check]

  (default)   First-time client enrollment and FRP install
  --upgrade   Upgrade management tools on an existing client
  --source    Source tree for --upgrade (default: this installer tree)
  --check     With --upgrade, report versions without changing files

An already-installed client is not re-enrolled. Use --upgrade / drlink system update product
for software updates. An Enrollment Code is not required for a software update.
EOF
}

# When this file is executed as a program, always honor CLI args. FRP_CLIENT_SOURCED
# is only for intentional `. install-client.sh` use; an exported leak from a prior
# sourced test must not make `install-client.sh --upgrade` become a silent no-op.
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --upgrade|upgrade)
        FRP_CLIENT_UPGRADE=1
        shift
        ;;
      --source)
        if [[ $# -lt 2 || "$2" == --* ]]; then
          echo "ERROR: --source requires a directory" >&2
          exit 2
        fi
        FRP_CLIENT_UPDATE_SOURCE="$2"
        shift 2
        ;;
      --check|--dry-run)
        FRP_CLIENT_UPDATE_CHECK=1
        shift
        ;;
      -h|--help)
        frp_client_installer_usage
        exit 0
        ;;
      zt1.*)
        # Short Zero-Touch opaque package from:
        #   curl -fsSL <public-installer> | sudo bash -s -- zt1.<payload>
        if ! frp_zero_touch_apply_package "$1"; then
          exit 1
        fi
        shift
        ;;
      *)
        echo "ERROR: unknown option: $1" >&2
        frp_client_installer_usage >&2
        exit 2
        ;;
    esac
  done
  if [[ "${FRP_CLIENT_UPGRADE:-}" == "1" ]]; then
    frp_client_upgrade_from_this_tree
    exit $?
  fi
  frp_client_main
  exit $?
fi
