#!/usr/bin/env python3
"""Bind a release-attest checkout to the canonical provenance-commit model.

Committed release metadata cannot name the commit that contains it. The
commit GitHub attests is therefore a follow-on provenance commit:

- provenance commit = checked-out HEAD = github.sha
- qualified content HEAD = manifest source_head = first parent of that commit
- immutable release ref = a stable or RC tag pointing at the provenance
  commit, or that commit's full SHA on the development channel
- a validated stable tag keeps the committed development manifest and
  reports effective publication channel stable, so attestation verification
  requires sourceRepositoryRef refs/tags/v<project version>
- generated artifacts = the only paths that differ from the content parent

Development git_ref is the content SHA. Stable and RC git_ref is the tag.
Do not invent a self-referential SHA to satisfy this check.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
RC_TAG_RE = re.compile(r"^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$")
# Generated by scripts/build-release-artifacts.sh. Product/runtime/CLI paths
# are intentionally absent.
PROVENANCE_PATHS = frozenset(
    {
        "SHA256SUMS",
        "release-manifest.json",
        "dist/bootstrap-client.sh",
        "dist/bootstrap-server.sh",
        "dist/bootstrap-client.ps1",
        "dist/uninstall-client.sh",
        "dist/uninstall-server.sh",
        "dist/sbom.spdx.json",
    }
)


class BindingError(Exception):
    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__("\n".join(errors))


@dataclass
class BindingFacts:
    project_version: str
    manifest_version: str
    channel: str
    git_ref: str
    source_head: str
    immutable_source_ref: str
    head: str
    parent: str | None
    input_ref: str
    workflow_ref: str
    workflow_sha: str
    changed_paths: tuple[str, ...]
    tag_commits: dict[str, str]
    clean: bool = True
    pass1_head: str = ""
    pass2_head: str = ""
    final_qualified_head: str = ""


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        check=False,
        capture_output=True,
        text=True,
    )


def _read_version(root: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in (root / "VERSION").read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def _changed_paths(root: Path, parent: str, head: str) -> tuple[str, ...]:
    proc = _git(root, "diff", "--name-status", "--find-renames", parent, head)
    if proc.returncode != 0:
        raise BindingError(
            ["git diff %s %s failed: %s" % (parent, head, proc.stderr.strip())]
        )
    paths: list[str] = []
    errors: list[str] = []
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        parts = line.split("\t")
        status = parts[0]
        if status.startswith(("R", "C", "D", "T")):
            errors.append("provenance commit must not rename or delete %s" % line)
            continue
        if not status.startswith(("M", "A")):
            errors.append("unsupported provenance diff status %s" % line)
            continue
        paths.append(parts[-1])
    if errors:
        raise BindingError(errors)
    return tuple(paths)


def load_facts(
    root: Path,
    input_ref: str,
    workflow_ref: str,
    workflow_sha: str,
) -> BindingFacts:
    root = root.resolve()
    status = _git(root, "status", "--porcelain")
    if status.returncode != 0:
        raise BindingError(["git status failed: %s" % status.stderr.strip()])
    clean = status.stdout.strip() == ""
    version = _read_version(root)
    manifest = json.loads((root / "release-manifest.json").read_text(encoding="utf-8"))
    head_proc = _git(root, "rev-parse", "HEAD")
    if head_proc.returncode != 0:
        raise BindingError(["git rev-parse HEAD failed"])
    head = head_proc.stdout.strip().lower()
    parent_proc = _git(root, "rev-parse", "--verify", "HEAD^1")
    parent = parent_proc.stdout.strip().lower() if parent_proc.returncode == 0 else None
    changed: tuple[str, ...] = ()
    if parent:
        changed = _changed_paths(root, parent, head)
    tags: dict[str, str] = {}
    for tag in (
        "v%s" % version.get("PROJECT_VERSION", ""),
        str(manifest.get("git_ref") or ""),
    ):
        if not tag or tag in tags:
            continue
        resolved = _git(root, "rev-parse", "--verify", "refs/tags/%s^{commit}" % tag)
        if resolved.returncode == 0:
            tags[tag] = resolved.stdout.strip().lower()
    return BindingFacts(
        project_version=version.get("PROJECT_VERSION", ""),
        manifest_version=str(manifest.get("project_version") or ""),
        channel=str(manifest.get("channel") or ""),
        git_ref=str(manifest.get("git_ref") or ""),
        source_head=str(manifest.get("source_head") or "").lower(),
        immutable_source_ref=str(manifest.get("immutable_source_ref") or ""),
        head=head,
        parent=parent,
        input_ref=input_ref.strip(),
        workflow_ref=workflow_ref.strip(),
        workflow_sha=workflow_sha.strip().lower(),
        changed_paths=changed,
        tag_commits=tags,
        clean=clean,
        pass1_head=os.environ.get("QUALIFICATION_PASS1_HEAD", "").strip().lower(),
        pass2_head=os.environ.get("QUALIFICATION_PASS2_HEAD", "").strip().lower(),
        final_qualified_head=os.environ.get("QUALIFICATION_FINAL_HEAD", "").strip().lower(),
    )


def _require_qualified_tag_heads(facts: BindingFacts, errors: list[str]) -> None:
    """PASS1, PASS2, and the final qualified HEAD are the tagged commit."""
    heads = (facts.pass1_head, facts.pass2_head, facts.final_qualified_head)
    if (
        not all(SHA_RE.fullmatch(item) for item in heads)
        or len(set(heads)) != 1
        or facts.final_qualified_head != facts.head
    ):
        errors.append(
            "PASS1_HEAD, PASS2_HEAD, and FINAL_QUALIFIED_HEAD must equal tag HEAD %s"
            % facts.head
        )


def evaluate(facts: BindingFacts) -> dict[str, str]:
    errors: list[str] = []
    # Committed channel stays in the manifest. This is the channel the
    # post-attestation verifier must use. A validated stable tag publishes
    # as stable without a follow-on commit.
    publication_channel = facts.channel
    validated_stable_tag = False
    if not facts.clean:
        errors.append(
            "worktree is not clean; release-attest requires the committed provenance tree"
        )
    if facts.project_version != facts.manifest_version:
        errors.append(
            "VERSION PROJECT_VERSION %s != manifest project_version %s"
            % (facts.project_version, facts.manifest_version)
        )
    if facts.channel not in ("stable", "development", "preview"):
        errors.append("unsupported channel %s" % facts.channel)
    if not facts.parent:
        errors.append("provenance commit must have a content parent")
    elif facts.source_head == facts.head:
        errors.append(
            "source_head %s must not equal the provenance commit %s; "
            "do not invent a self-referential SHA"
            % (facts.source_head, facts.head)
        )
    elif facts.source_head != facts.parent:
        errors.append(
            "source_head %s != content parent %s"
            % (facts.source_head, facts.parent)
        )
    if facts.immutable_source_ref != facts.git_ref:
        errors.append(
            "immutable_source_ref %r != git_ref %r"
            % (facts.immutable_source_ref, facts.git_ref)
        )
    unexpected = sorted(set(facts.changed_paths) - PROVENANCE_PATHS)
    if facts.parent and not facts.changed_paths:
        errors.append("provenance commit does not change generated provenance files")
    if "release-manifest.json" not in facts.changed_paths:
        errors.append("provenance commit must update release-manifest.json")
    if unexpected:
        errors.append(
            "provenance commit changes non-generated paths: %s" % ", ".join(unexpected)
        )
    if facts.workflow_sha != facts.head:
        errors.append(
            "github.sha %s != checked-out provenance HEAD %s"
            % (facts.workflow_sha, facts.head)
        )

    expected_tag = "v%s" % facts.project_version
    if facts.channel == "stable":
        if facts.git_ref != expected_tag:
            errors.append(
                "stable git_ref %r != %s" % (facts.git_ref, expected_tag)
            )
        tag_commit = facts.tag_commits.get(expected_tag)
        if tag_commit is None:
            errors.append("tag %s does not exist" % expected_tag)
        elif tag_commit != facts.head:
            errors.append(
                "%s resolves to %s, not provenance HEAD %s"
                % (expected_tag, tag_commit, facts.head)
            )
        if facts.input_ref not in (expected_tag, facts.head):
            errors.append(
                "ref %r is neither %s nor %s" % (facts.input_ref, expected_tag, facts.head)
            )
        want_ref = "refs/tags/%s" % expected_tag
        if facts.workflow_ref != want_ref:
            errors.append(
                "dispatch this workflow from %s, not %s"
                % (want_ref, facts.workflow_ref)
            )
        _require_qualified_tag_heads(facts, errors)
    else:
        git_ref = facts.git_ref
        if SHA_RE.fullmatch(git_ref):
            if git_ref != facts.source_head:
                errors.append(
                    "%s git_ref %s != qualified content source_head %s"
                    % (facts.channel, git_ref, facts.source_head)
                )
            qualified_tag = "v%s" % facts.project_version
            tag_at_head = facts.tag_commits.get(qualified_tag) == facts.head
            if facts.input_ref == facts.head:
                pass
            elif facts.input_ref == qualified_tag and tag_at_head:
                want_ref = "refs/tags/%s" % qualified_tag
                if facts.workflow_ref != want_ref:
                    errors.append(
                        "dispatch this workflow from %s, not %s"
                        % (want_ref, facts.workflow_ref)
                    )
                _require_qualified_tag_heads(facts, errors)
                validated_stable_tag = True
            else:
                errors.append(
                    "%s ref must be the provenance commit SHA %s"
                    % (facts.channel, facts.head)
                )
        elif RC_TAG_RE.fullmatch(git_ref):
            tag_commit = facts.tag_commits.get(git_ref)
            if tag_commit is None:
                errors.append("RC tag %s does not exist" % git_ref)
            elif tag_commit != facts.head:
                errors.append(
                    "%s resolves to %s, not provenance HEAD %s"
                    % (git_ref, tag_commit, facts.head)
                )
            if facts.input_ref not in (facts.head, git_ref):
                errors.append(
                    "%s ref must be %s or %s" % (facts.channel, facts.head, git_ref)
                )
            want_ref = "refs/tags/%s" % git_ref
            if facts.workflow_ref != want_ref:
                errors.append(
                    "dispatch this workflow from %s, not %s"
                    % (want_ref, facts.workflow_ref)
                )
        else:
            errors.append(
                "%s git_ref must be a 40-char content SHA or RC tag, got %r"
                % (facts.channel, git_ref)
            )
        if facts.source_head and not SHA_RE.fullmatch(facts.source_head):
            errors.append("source_head must be a 40-character SHA")

    if errors:
        raise BindingError(errors)
    if validated_stable_tag:
        publication_channel = "stable"
    return {
        "expected_tag": expected_tag,
        "release_commit": facts.head,
        "content_commit": facts.source_head,
        "channel": publication_channel,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args(argv)
    root = Path(args.root)
    try:
        facts = load_facts(
            root,
            os.environ.get("INPUT_REF", ""),
            os.environ.get("WORKFLOW_REF", ""),
            os.environ.get("WORKFLOW_SHA", ""),
        )
        outputs = evaluate(facts)
    except BindingError as exc:
        for err in exc.errors:
            print("ERROR: %s" % err, file=sys.stderr)
        print("REF_BINDING=FAIL", file=sys.stderr)
        return 1
    for key, value in outputs.items():
        print("%s=%s" % (key, value))
    print("REF_BINDING=PASS", file=sys.stderr)
    print("CONTENT_COMMIT=%s" % outputs["content_commit"], file=sys.stderr)
    print("PROVENANCE_COMMIT=%s" % outputs["release_commit"], file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
