# Unpublished template for a future community/private tap only.
# This is NOT official Homebrew core support and is not published as a tap yet.
# v2.3.1 was not manufactured. Do not set url to a future v2.4.0 tag before
# that immutable tag exists. The documented stable baseline is v2.3.0; this
# formula tracks the current development client layout and is not that release.
# Fill url and sha256 from an immutable release tarball only after that tag exists.
class DataRelayLink < Formula
  desc "Data Relay Link client for Apple Silicon macOS"
  homepage "https://github.com/datarelay-labs/datarelay-link"
  version "2.4.0"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on macos: :big_sur

  def install
    libexec.install "install-client.sh", "uninstall-client.sh", "VERSION",
                    "release-manifest.json", "lib", "tools", "client"
    %w[drlink frp-client].each do |name|
      (bin/name).write <<~SH
        #!/bin/bash
        exec "#{libexec}/tools/#{name}" "$@"
      SH
      chmod 0755, bin/name
    end
  end

  def caveats
    <<~EOS
      This formula installs the client tools only. Use the enrollment command
      generated by your Data Relay Link server to enroll and start the LaunchDaemon.
      This template is not published. Do not fetch a nonexistent release tag.
    EOS
  end

  test do
    assert_match "PROJECT_VERSION=2.4.0", (libexec/"VERSION").read
    assert_predicate bin/"drlink", :executable?
  end
end
