name: Engineering System

on:
  pull_request:

permissions:
  contents: read

jobs:
  adoption-compliance:
    uses: datarelay-labs/engineering-system/.github/workflows/adoption-compliance.yml@4e9555ea0783459469765a07cb20c5dbd6a1ceb0

  enforcement-reconcile:
    uses: datarelay-labs/engineering-system/.github/workflows/enforcement-check.yml@4e9555ea0783459469765a07cb20c5dbd6a1ceb0
